### ISSUE TITLE
404 on comments

### ISSUE THREAD

**Issue by katosdev** [katosdev/MyTracker#1]
Posting new comments redirects to /issue-{pid} and not to /tracker/issue-{pid}

**Comment by ghost** [comment]
quick question why does this plugin require another jquery? doesen mybb already use jquery

**Comment by katosdev** [comment]
It's an extension of the current library I believe, but it was coded by Tomm from Mybb, so I am unsure how he set it up fully without diving into it deeper than I have already done so.

**Comment by katosdev** [comment]
@LiveChief 

Fixed it commit : https://github.com/katosdev/MyTracker/commit/1fb200df34bd108cd3a608409b7c792dc184e9d4

With thanks to:
Tom Kent
